### ISSUE TITLE
domain unavailable

### ISSUE THREAD

**Issue by ethinallen** [HarrisonHall/hachha.dev#1]
<img width="954" alt="Screen Shot 2023-03-16 at 11 01 19 AM" src="https://user-images.githubusercontent.com/34930628/225711408-e0cca361-cb75-4348-a86a-e4af3c1930d1.png">

domain unavailable

**Comment by HarrisonHall** [comment]
I bought it yesterday lmao.
I actually only bought my harrisonchristianhall.com domain because a friend threatened to buy it himself in highschool.
